<?php
    //Footer Section Begin
echo "<footer class='footer set-bg' data-setbg='img/footer-bg.jpg'>";
echo "    <div class='container'>";
echo "        <div class='row'>";
echo "            <div class='col-lg-12'>";
echo "                <div class='logo__carousel owl-carousel'>";
echo "                    <div class='logo__carousel__item'>";
echo "                        <a href='#'><img src='img/logo/logo-1.png' alt=''></a>";
echo "                    </div>";
echo "                    <div class='logo__carousel__item'>";
echo "                        <a href='#'><img src='img/logo/logo-2.png' alt=''></a>";
echo "                    </div>";
echo "                    <div class='logo__carousel__item'>";
echo "                        <a href='#'><img src='img/logo/logo-3.png' alt=''></a>";
echo "                    </div>";
echo "                    <div class='logo__carousel__item'>";
echo "                        <a href='#'><img src='img/logo/logo-4.png' alt=''></a>";
echo "                    </div>";
echo "                    <div class='logo__carousel__item'>";
echo "                        <a href='#'><img src='img/logo/logo-5.png' alt=''></a>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
echo "    <div class='container'>";
echo "        <div class='footer__content'>";
echo "            <div class='row'>";
echo "                <div class='col-lg-3 col-md-6 col-sm-6'>";
echo "                    <div class='footer__about'>";
echo "                        <div class='footer__logo'>";
echo "                            <a href='#'><img src='img/logo.png' alt=''></a>";
echo "                        </div>";
echo "                        <h4>(123) 456-78-91096</h4>";
echo "                        <ul>";
echo "                            <li>Ernser Vista Suite 437, NY</li>";
echo "                            <li>Info.colorlib@gmail.com</li>";
echo "                        </ul>";
echo "                        <div class='footer__social'>";
echo "                            <a href='#'><i class='fa fa-facebook'></i></a>";
echo "                            <a href='#'><i class='fa fa-twitter'></i></a>";
echo "                            <a href='#'><i class='fa fa-linkedin'></i></a>";
echo "                            <a href='#'><i class='fa fa-youtube-play'></i></a>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "                <div class='col-lg-3 offset-lg-1 col-md-5 offset-md-1 col-sm-6'>";
echo "                    <div class='footer__widget'>";
echo "                        <h4>Quick Link</h4>";
echo "                        <ul>";
echo "                            <li><a href='./index.php'>Home</a></li>";
echo "                            <li><a href='./availableroute_bus.php'>Bus Available</a></li>";
echo "                            <li><a href='./availableroute_date.php'>Date Available</a></li>";
echo "                        </ul>";
echo "                        <ul>";
echo "                            <li><a href='./gallery.php'>Our Gallery</a></li>";
echo "                            <li><a href='./about.php'>About Us</a></li>";
echo "                            <li><a href='./contact.php'>Contact</a></li>";
echo "                        </ul>";
echo "                    </div>";
echo "                </div>";
echo "                <div class='col-lg-5 col-md-8 col-sm-12'>";
echo "                    <div class='footer__newslatter'>";
echo "                        <h4>Subscribe our newlatester</h4>";
echo "                        <form action='#'>";
echo "                            <input type='text' placeholder='Your E-mail Address'>";
echo "                            <button type='submit'>Subscribe</button>";
echo "                        </form>";
echo "                        <div class='footer__newslatter__find'>";
echo "                            <h5>Find Us:</h5>";
echo "                            <div class='footer__newslatter__find__links'>";
echo "                                <a href='#'><i class='fa fa-tripadvisor'></i></a>";
echo "                                <a href='#'><i class='fa fa-map-o'></i></a>";
echo "                                <a href='#'><i class='fa fa-dribbble'></i></a>";
echo "                                <a href='#'><i class='fa fa-forumbee'></i></a>";
echo "                            </div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "        <div class='footer__copyright'>";
echo "            <div class='row'>";
echo "                <div class='col-lg-7 col-md-7'>";
echo "                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->";
echo "                    <div class='footer__copyright__text'>";
echo "                        <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class='fa fa-heart' aria-hidden='true'></i> by <a href='https://colorlib.com' target='_blank'>Colorlib</a></p>";
echo "                    </div>";
echo "                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->";
echo "                </div>";
echo "                <div class='col-lg-5 col-md-5'>";
echo "                    <ul class='footer__copyright__links'>";
echo "                        <li><a href='#'>Terms Of Use</a></li>";
echo "                        <li><a href='#'>Privacy Policy</a></li>";
echo "                    </ul>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
echo "</footer>";
    //Footer Section End
?>